
image: cirrusci/flutter:latest

stages:
  - test
  - build

test:flutter:
  stage: test
  script:
    - flutter test

build:bundle:
  stage: build
  script:
    - flutter build appbundle
  artifacts:
    paths:
      - build/app/outputs/bundle